import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Megaphone, Mail, Instagram, Type, FileText } from 'lucide-react';

export function MarketingModule() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900">Marketing & Content AI</h1>
          <p className="text-gray-500 mt-1">Autonomous multi-channel campaign generation</p>
        </div>
        <button className="flex items-center space-x-2 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg font-medium transition-colors shadow-sm">
          <Type className="w-4 h-4 mr-2" />
          Generate New Campaign
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 space-y-6">
          <Card>
            <CardHeader className="pb-3 border-b border-gray-100">
              <CardTitle className="text-sm flex items-center">
                <FileText className="w-4 h-4 mr-2 text-indigo-500"/>
                Active Generators
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4 p-0">
              <div className="divide-y divide-gray-100">
                <div className="p-4 hover:bg-gray-50 cursor-pointer flex justify-between items-center transition-colors">
                  <div className="flex items-center">
                    <Instagram className="w-5 h-5 text-pink-600 mr-3"/>
                    <span className="font-medium text-sm text-gray-900">Social Media Posts</span>
                  </div>
                  <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                </div>
                <div className="p-4 hover:bg-gray-50 cursor-pointer flex justify-between items-center border-l-2 border-indigo-500 bg-indigo-50/20 transition-colors">
                  <div className="flex items-center">
                    <Mail className="w-5 h-5 text-blue-500 mr-3"/>
                    <span className="font-medium text-sm text-indigo-900">Email Newsletters</span>
                  </div>
                  <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                </div>
                <div className="p-4 hover:bg-gray-50 cursor-pointer flex justify-between items-center transition-colors">
                  <div className="flex items-center">
                    <Megaphone className="w-5 h-5 text-amber-500 mr-3"/>
                    <span className="font-medium text-sm text-gray-900">Ad Copy (Google/Meta)</span>
                  </div>
                  <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="lg:col-span-2">
          <Card className="h-full border-indigo-100 shadow-sm">
            <CardHeader className="bg-white border-b border-gray-100 flex flex-row items-center justify-between pb-4">
              <div>
                <CardTitle>Email Campaign: Spring Promo</CardTitle>
                <p className="text-xs text-gray-500 mt-1">Generated by Mistral Large • 10 mins ago</p>
              </div>
              <div className="flex space-x-2">
                <button className="px-3 py-1.5 text-xs font-semibold text-indigo-700 bg-indigo-50 rounded-md hover:bg-indigo-100">Edit</button>
                <button className="px-3 py-1.5 text-xs font-semibold text-white bg-indigo-600 rounded-md hover:bg-indigo-700">Schedule Launch</button>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="bg-gray-50 rounded-xl p-6 border border-gray-200">
                <div className="mb-4">
                  <p className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-1">Subject Line A/B Tests</p>
                  <ul className="list-disc list-inside text-sm text-gray-900 space-y-1">
                    <li>Refresh Your Workspace: 20% Off Desk Essentials 🌱</li>
                    <li>The Spring Upgrade Your Setup Deserves</li>
                  </ul>
                </div>
                <hr className="border-gray-200 my-4" />
                <div className="prose prose-sm max-w-none text-gray-700">
                  <p>Hi [Name],</p>
                  <p>Spring is the perfect time for a reset—especially where you spend most of your day.</p>
                  <p>We've noticed you've been checking out our Ergonomic Series. To help you build the perfect setup for warmer weather and longer days, we're unlocking an exclusive 20% discount on all desk accessories this week.</p>
                  <p><strong>Top picks for you:</strong></p>
                  <ul>
                    <li>The ErgoWrist Rest (Now $19.99)</li>
                    <li>Dual Monitor Spring Arm (Now $79.99)</li>
                  </ul>
                  <p>Click below to claim your discount before it expires on Friday.</p>
                </div>
                <div className="mt-6 flex justify-center">
                  <div className="bg-indigo-600 text-white px-8 py-3 rounded-md font-bold text-sm cursor-pointer shadow-sm">
                    Claim 20% Off Now
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
